import { StatusCodes } from "http-status-codes";

const HTTP_CREATED = StatusCodes.CREATED;
const HTTP_OK = StatusCodes.OK;
const HTTP_UNAUTHORIZED = StatusCodes.UNAUTHORIZED;
const HTTP_FORBIDDEN = StatusCodes.FORBIDDEN;
const HTTP_NOT_FOUND = StatusCodes.NOT_FOUND;
const HTTP_METHOD_NOT_ALLOWED = StatusCodes.METHOD_NOT_ALLOWED;
const HTTP_UNPROCESSABLE_ENTITY = StatusCodes.UNPROCESSABLE_ENTITY;
const HTTP_INTERNAL_SERVER_ERROR = StatusCodes.INTERNAL_SERVER_ERROR;
const HTTP_BADREQUEST = StatusCodes.BAD_REQUEST
const HTTP_CONFLICT = StatusCodes.CONFLICT


export {
    HTTP_CREATED,
    HTTP_OK,
    HTTP_UNAUTHORIZED,
    HTTP_FORBIDDEN,
    HTTP_NOT_FOUND,
    HTTP_METHOD_NOT_ALLOWED,
    HTTP_UNPROCESSABLE_ENTITY,
    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_BADREQUEST,
    HTTP_CONFLICT
}